/**
 * Seed script — Legal Content (FAQ, Privacy Policy, Terms of Service)
 * Run once: node server/scripts/seed.legal.content.js
 * Safe to re-run: uses upsert so it won't duplicate documents.
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env.local') });
const mongoose = require('mongoose');
require('../models/legal.content');

const LegalContent = mongoose.model('LegalContent');

const LAST_UPDATED = '2026-03-24';           // winkyRules
const DOC_LAST_UPDATED = 'August 24, 2026';  // faq, privacyPolicy, termsOfService

const seeds = [
    {
        type: 'faq',
        lastUpdated: DOC_LAST_UPDATED,
        categories: [
            {
                category: "ABOUT WINKY",
                items: [
                    { question: "What is Winky?", answer: "Winky is a nearby social communication app designed to help people make The First Hello™.\n\nWinky lets you discover and communicate with other Winky users who are nearby — without first needing their phone number, email address, or social media information.\n\nYou may notice someone nearby at a coffee shop, on campus, at an event, in your building, at the gym, or simply out in the world. Instead of wondering how to approach them, Winky gives you another way to say hello.\n\nBecause every friend was once a stranger." },
                    { question: "What does \"The First Hello™\" mean?", answer: "Most communication apps help you talk to people you already know. Winky is different.\n\nWinky is designed to help you make the first connection with someone nearby — the person you haven't met yet, don't have contact information for, or perhaps would simply feel more comfortable approaching through a message.\n\nSometimes all it takes is a simple hello. That's The First Hello™." },
                    { question: "How does Winky work?", answer: "Winky uses your location to show other Winky users who are nearby and have chosen to be discoverable.\n\nOpen Discover to see people around you. If someone catches your attention, you can view the information they have chosen to share and send them a Wink or message. If they respond, the conversation can begin.\n\nYou don't need to exchange phone numbers or personal contact information just to say hello." },
                    { question: "Is Winky a dating app?", answer: "Winky can certainly be used to meet someone you're interested in, but Winky isn't limited to dating. It's a First Hello Platform.\n\nYou might use Winky to meet a new friend, introduce yourself to someone at an event, connect with another student, meet someone in your neighbourhood, start a professional conversation, or simply say hello to someone nearby.\n\nWinky is about creating the opportunity for a connection. What happens after the first hello is up to you." },
                    { question: "How is Winky different from other messaging and social apps?", answer: "Most messaging apps begin after you've already made the connection. You usually need someone's phone number, username, email address, social media profile, or other contact information before you can communicate.\n\nWinky starts one step earlier. It helps you discover and communicate with people who are physically nearby — even when you've never met and haven't exchanged contact information.\n\nThat's what makes Winky different. Winky is about making The First Hello™." },
                    { question: "Is Winky free?", answer: "Winky is free to download and use for the features made available without charge.\n\nWinky may introduce optional premium features or services in the future. If a feature requires payment, you will be informed before purchasing it." },
                ]
            },
            {
                category: "DISCOVER & LOCATION",
                items: [
                    { question: "What is the Discover screen?", answer: "Discover is where you can see other discoverable Winky users who are nearby. Think of it as your window into the people around you.\n\nRather than searching through people who may be miles away, Winky is built around real-world proximity — helping you discover people who are actually around you." },
                    { question: "How close does someone have to be for me to discover them?", answer: "Winky gives you different distance settings so you can decide how wide an area you want to explore.\n\nDepending on your selected setting, you can discover Winky users within approximately:\n\n• 75 feet\n• 300 feet\n• 1,000 feet\n• ½ mile\n\nOnly users who meet your selected preferences and are available to be discovered will appear." },
                    { question: "Does Winky show my exact location?", answer: "No.\n\nWinky uses location information to determine which users are nearby and to make the Discover feature work. Winky is not intended to display your exact street address or precise location to other users.\n\nThe purpose is to help you discover people nearby — not to tell someone exactly where you are standing." },
                    { question: "Why does Winky need access to my location?", answer: "Nearby discovery is at the heart of Winky.\n\nLocation access allows Winky to determine which users are within your selected discovery range and makes The First Hello™ possible.\n\nYou can control location permissions through your device settings. Certain nearby-discovery features may not work properly if location access is disabled." },
                    { question: "Can I control who I discover?", answer: "Yes.\n\nWinky's filters allow you to customize the types of people you would like to discover based on the options available within the app.\n\nYour preferences help make your Discover experience more relevant to you." },
                    { question: "Can I stop other people from discovering me?", answer: "Yes.\n\nWinky gives you controls over your visibility and nearby-discovery experience.\n\nIf you don't want to appear to other users, use the applicable privacy or visibility setting within Winky." },
                ]
            },
            {
                category: "PRIVACY & SECURITY",
                items: [
                    { question: "Do I have to give someone my phone number to talk to them?", answer: "No. That's one of the most important features of Winky.\n\nYou can make an initial connection and communicate through Winky without giving another user your personal phone number, email address, or social media account.\n\nYou decide whether you ever want to share additional personal information." },
                    { question: "Are my Winky messages and calls private?", answer: "Winky is designed with privacy and security in mind.\n\nWinky communications protected by end-to-end encryption are encrypted so that the content is available only to the participants in that communication. This helps protect your private conversations from being read or listened to by unauthorized third parties.\n\nFor complete information about how Winky collects, uses, stores, and protects information, please review the Winky Privacy Policy." },
                    { question: "What is end-to-end encryption?", answer: "End-to-end encryption is a security technology designed to protect the content of a communication as it travels between participants.\n\nIn simple terms, an encrypted Winky conversation is protected so that the people participating in that conversation are the ones who can access its contents.\n\nIt adds an important layer of privacy and security to your communications." },
                    { question: "Does Winky sell my private conversations or personal information to advertisers?", answer: "Winky does not sell the contents of your private messages or calls to advertisers.\n\nFor details about the information Winky collects and how that information may be used, please refer to the Winky Privacy Policy." },
                ]
            },
            {
                category: "YOUR PROFILE",
                items: [
                    { question: "What name will other people see?", answer: "When you create your Winky account, you choose how you want to be identified to other users.\n\nWinky allows you to use the name you have chosen or an available username, depending on your profile settings.\n\nThis gives you greater control over how you introduce yourself to people nearby." },
                    { question: "Do I have to use my real name?", answer: "No.\n\nYou can choose how you would like to identify yourself on Winky, subject to Winky's rules and username requirements.\n\nWhatever name you choose, you may not impersonate another person or use Winky in a misleading, fraudulent, abusive, or unlawful manner." },
                    { question: "Can I change my username?", answer: "Your username may be changed once, so choose carefully.\n\nYour username is part of how other people recognize you on Winky." },
                ]
            },
            {
                category: "COMMUNICATING",
                items: [
                    { question: "Can I make voice or video calls on Winky?", answer: "Yes.\n\nWinky includes communication features that allow users to connect beyond text messaging, including voice and video communication where available.\n\nYou can start with a simple message and decide for yourself how you would like the conversation to continue." },
                    { question: "Do I have to respond if someone sends me a Wink or message?", answer: "No. You are always in control of whether you respond.\n\nReceiving a Wink or message never creates an obligation to communicate. If you're not interested, you can simply choose not to respond.\n\nIf the communication is unwanted or inappropriate, you can block or report the user." },
                ]
            },
            {
                category: "SAFETY & REPORTING",
                items: [
                    { question: "How old do I have to be to use Winky?", answer: "You must be at least 18 years old to create or use a Winky account.\n\nWinky is not intended for anyone under the age of 18." },
                    { question: "What happens if I block someone?", answer: "Blocking is designed to immediately stop unwanted interaction.\n\nWhen you block another user:\n\n• They cannot message you.\n• They cannot call you.\n• You will no longer appear to each other through nearby discovery.\n• You can unblock them later if you change your mind.\n\nThe other person's access to you through Winky is restricted for as long as the block remains in place." },
                    { question: "How do I report someone?", answer: "If you believe someone is behaving inappropriately or violating Winky's rules, you can report that person from their profile, a chat, or the nearby Discover screen.\n\nReports are submitted for review and may result in restrictions or the account being banned when appropriate.\n\nBlocking and reporting are separate features. If you don't want someone to contact or discover you, you should also block that user." },
                    { question: "What kind of behaviour is not allowed on Winky?", answer: "Winky is intended to help people make genuine, respectful connections.\n\nUsers may not use Winky to harass, threaten, impersonate, defraud, exploit, stalk, intimidate, or otherwise harm another person. Illegal activity and other conduct prohibited by Winky's Terms of Service are also not permitted.\n\nYou should never feel obligated to respond to another user. If someone's behaviour makes you uncomfortable, you can end the conversation, block them, and report them when appropriate." },
                    { question: "Does Winky guarantee that another user's identity or profile information is accurate?", answer: "No.\n\nWinky provides a platform for people to discover and communicate with one another, but Winky cannot guarantee that every statement, photograph, name, username, or other piece of information supplied by another user is accurate.\n\nUse good judgment when communicating with someone you don't know." },
                    { question: "What should I keep in mind when meeting someone for the first time?", answer: "Winky helps people make introductions, but you remain in control of whether a conversation goes any further.\n\nBe thoughtful about the personal information you share. If you decide to meet someone you first connected with through Winky, use common sense and appropriate precautions.\n\nYou never have to continue a conversation or meet another user simply because you connected on Winky." },
                ]
            },
            {
                category: "YOUR ACCOUNT",
                items: [
                    { question: "What happens when I delete my Winky account?", answer: "Deleting your account permanently removes your account and identifying profile information from Winky's active systems in accordance with the Winky Privacy Policy.\n\nMessages or calls that you previously sent to other users may remain in those users' conversation histories and may appear as having come from a deleted user.\n\nCertain limited, non-public information may also be retained when necessary for security, fraud prevention, enforcement of bans, legal obligations, or other purposes described in the Winky Privacy Policy.\n\nAccount deletion is intended to be permanent." },
                    { question: "Can someone who has been banned simply delete their account and create another one?", answer: "Winky has security measures designed to help prevent users who have been banned from simply deleting an account and immediately returning with a new one.\n\nThese measures are designed to protect the Winky community while limiting the personal information retained for this purpose.\n\nAdditional information is available in the Winky Privacy Policy." },
                    { question: "Where can I learn more about my privacy and Winky's rules?", answer: "For complete information about privacy, data practices, account deletion, acceptable use, your rights, and the rules governing Winky, please review the Winky Privacy Policy and the Winky Terms of Service.\n\nThese documents are available within the Winky app." },
                ]
            },
            {
                category: "THE FIRST HELLO™",
                items: [
                    { question: "Why was Winky created?", answer: "There are people around us every day whom we never meet.\n\nSometimes we don't know what to say. Sometimes we're uncomfortable approaching someone. And sometimes the moment simply passes.\n\nWinky was created to give people another way to make that first connection.\n\nYou don't need their phone number.\nYou don't need their email address.\nYou don't need their social media.\n\nSometimes you just need a way to say: Hello.\n\nWINKY® — The First Hello™\nBecause every friend was once a stranger." },
                ]
            },
        ]
    },
    {
        type: 'privacyPolicy',
        lastUpdated: DOC_LAST_UPDATED,
        sections: [
            { number: null, title: null, body: "Effective Date: August 24, 2026\nLast Updated: August 24, 2026\n\nWelcome to WINKY® — The First Hello™.\n\nWINKY® (\"Winky,\" \"we,\" \"us,\" or \"our\") is a mobile application owned and operated by Hudson Watch Inc. that helps adults discover and communicate with other people nearby.\n\nThis Privacy Policy explains what personal information we collect, why we collect it, how we use and protect it, when it may be shared, and the choices available to you." },
            { number: "1", title: "Introduction", body: "At Winky, we believe meaningful connections often begin with a simple hello. We also believe that starting that hello should not require giving up your privacy.\n\nBy creating a Winky account or using Winky, you acknowledge the practices described in this Privacy Policy." },
            { number: "2", title: "Our Approach to Privacy", body: "Privacy is an important part of the Winky experience. Two principles are particularly important: your exact location is not displayed to other Winky users, and your private Winky chat messages are protected by end-to-end encryption.\n\nWinky uses location information to provide its nearby-discovery functionality. Other users may be shown that you are within a selected proximity or discovery range, but Winky does not display your exact GPS coordinates, street address or precise physical location to other users.\n\nPrivate Winky chat messages are protected by end-to-end encryption. This means that the readable content of an encrypted message is available only to the participants in the conversation. Winky, Hudson Watch Inc., our developers, programmers, service administrators and hosting providers do not possess the encryption keys necessary to read the content of your end-to-end encrypted private chat messages.\n\nWinky may, however, process limited technical information associated with communications, such as sender and recipient account identifiers, timestamps, delivery information, IP addresses or other communications metadata when necessary to transmit messages, operate the Service, maintain security or troubleshoot technical issues.\n\nEnd-to-end encryption protects the content of your private chat messages. It does not necessarily prevent Winky from processing technical information associated with those communications." },
            { number: "3", title: "Eligibility and Age Requirement", body: "Winky is intended exclusively for adults who are 18 years of age or older. You may not create an account or use Winky if you are under 18 years of age.\n\nWe do not knowingly permit anyone under 18 to use Winky or knowingly collect personal information from anyone under 18. If we learn that an account belongs to a person under 18, we may immediately suspend or terminate the account and delete the associated personal information.\n\nIf you believe that a person under 18 is using Winky, please contact us using the information provided at the end of this Privacy Policy." },
            { number: "4", title: "Information We Collect", body: "We collect information necessary to create and operate your Winky account, provide Winky's nearby-discovery and communication features, maintain the security of the Service and improve Winky.\n\nWhen you create or maintain a Winky account, we may collect information such as:\n\n• mobile telephone number;\n• display name;\n• username, if you choose to create one;\n• profile photograph;\n• bio;\n• age or age range;\n• gender;\n• sign-in or authentication information; and\n• other profile information you choose to provide.\n\nYour telephone number may be used for registration, authentication, verification, account security and account recovery. Your telephone number is not displayed publicly on your Winky profile.\n\nCertain profile information that you choose to provide may be visible to other Winky users according to Winky's features and your applicable settings. Please do not include information in your profile or bio that you do not want other Winky users to see." },
            { number: "5", title: "Location and Proximity Information", body: "Location information is necessary for Winky's nearby-discovery functionality. With your permission, Winky processes and stores information about your device's location so that the Service can determine which other Winky users are within the applicable discovery range.\n\nWe may use location and proximity information to:\n\n• identify Winky users within a selected discovery range;\n• determine approximate proximity between users;\n• determine whether users are within one another's selected discovery ranges;\n• provide nearby-discovery functionality;\n• operate visibility controls;\n• maintain and improve location-based features;\n• prevent fraud, abuse or misuse of the Service; and\n• diagnose technical problems.\n\nYour Exact Location Is Not Displayed\n\nWinky does not display your exact GPS coordinates, street address or precise geographic location to other Winky users. Instead, Winky uses your location to determine proximity and whether other users fall within the discovery range you select.\n\nWinky may provide discovery ranges such as:\n\n• Closest — 75 ft\n• Nearby — 300 ft\n• Walkable — 1,000 ft\n• Area — ½ mile\n\nThese settings determine the geographic range within which Winky may help you discover or become visible to other users. They do not disclose your exact location to those users.\n\nLocation Permissions\n\nYour device controls the location permissions available to Winky. Depending on the permission you select, Winky may receive and process your location while you are actively using Winky, or while Winky is operating in the background if you have granted the applicable permission.\n\nYou may change Winky's location permission through your device settings. If you disable location access, some or all of Winky's nearby-discovery functionality may no longer operate correctly.\n\nBecause a user's current location may change as the user moves, Winky may update stored location information in order to provide its proximity-based features." },
            { number: "6", title: "Private Chat Messages and End-to-End Encryption", body: "Private Winky chat messages are protected by end-to-end encryption. End-to-end encryption is designed so that only the participants in an encrypted conversation possess the ability to read the content of their messages.\n\nWinky does not possess the encryption keys required to decrypt and read the content of private encrypted chat messages. This means Winky, Hudson Watch Inc., our developers, programmers, administrators and hosting providers cannot read the content of your end-to-end encrypted private chat messages.\n\nCommunications Metadata\n\nAlthough Winky cannot read encrypted private message content, our systems may process and retain technical information necessary to provide the messaging service. This may include:\n\n• sender and recipient account identifiers;\n• timestamps;\n• delivery status;\n• IP addresses;\n• device or application information;\n• technical routing information; and\n• other limited communications metadata necessary to operate, secure or troubleshoot the Service.\n\nUser Reports\n\nIf Winky allows you to report another user, you may voluntarily provide information, screenshots or other materials relating to that report. Information voluntarily submitted to Winky as part of a report may be reviewed by us for safety, investigation, enforcement and support purposes.\n\nSubmitting information in a report does not give Winky general access to your other end-to-end encrypted conversations." },
            { number: "7", title: "Photos, Camera and Media", body: "With your permission, Winky may access your device's camera or photo library when necessary to allow you to:\n\n• create or change your profile photograph;\n• take photographs using supported Winky features;\n• select photographs or supported media from your device; or\n• share supported media through Winky.\n\nWinky will request the applicable device permission where required. You may change camera and photo permissions through your device settings." },
            { number: "8", title: "Device, Usage and Technical Information", body: "When you use Winky, we may automatically collect limited technical information necessary to operate, secure, diagnose and improve the Service. This information may include:\n\n• device type;\n• operating system and version;\n• Winky application version;\n• Internet Protocol (IP) address;\n• unique or pseudonymous device identifiers;\n• language and regional settings;\n• application activity;\n• crash and diagnostic information;\n• security events;\n• date and time of access; and\n• information concerning the operation and performance of Winky features.\n\nWe may use this information to maintain the Service, correct errors, prevent abuse, protect security, understand application performance and improve Winky." },
            { number: "9", title: "How We Use Personal Information", body: "We may use personal information to:\n\n• create and administer your Winky account;\n• authenticate and verify your account;\n• provide nearby-discovery functionality;\n• determine proximity between users;\n• apply your visibility and discovery preferences;\n• allow users to communicate;\n• transmit end-to-end encrypted messages;\n• provide voice or video communication features where available;\n• display profile information you choose to make available;\n• provide customer support;\n• respond to reports, complaints and safety concerns;\n• enforce our Terms of Service;\n• detect, investigate and prevent fraud, abuse and security threats;\n• troubleshoot technical problems;\n• analyze and improve Winky's performance;\n• develop and improve Winky features;\n• comply with applicable legal obligations; and\n• protect Winky, our users and the public.\n\nWe will not use personal information for materially different purposes without providing appropriate notice and obtaining consent where required by applicable law." },
            { number: "10", title: "Visibility and Your Choices", body: "Winky provides controls that allow you to manage aspects of your visibility and profile. Depending on the features available in your version of Winky, you may be able to control:\n\n• whether you are visible to nearby users;\n• your discovery distance or range;\n• your display name or username;\n• your profile photograph;\n• your bio;\n• other profile information; and\n• other privacy or visibility preferences.\n\nChanging a visibility setting affects how Winky presents you to other users. It does not necessarily prevent Winky from processing information required to maintain your account, protect the Service or provide features you have enabled." },
            { number: "11", title: "Service Providers", body: "Winky uses third-party technology and service providers to help operate, maintain, secure and improve the Service. Depending on the feature being used, these providers currently include services supplied by:\n\n• Amazon Web Services (AWS);\n• Amazon S3;\n• Amazon Simple Email Service (SES);\n• MongoDB Atlas;\n• Twilio;\n• Firebase Crashlytics;\n• Firebase Analytics;\n• Google Ads on-device conversion;\n• Google Sign-In; and\n• Apple.\n\nThese services may provide functions such as cloud infrastructure, data storage, communications, account authentication, analytics, crash reporting, advertising measurement and other technical services. Third-party providers may process information necessary to perform their services for Winky and may have their own privacy and security obligations.\n\nThe use of third-party infrastructure does not provide those service providers with the encryption keys necessary to read the content of Winky's end-to-end encrypted private chat messages." },
            { number: "12", title: "When We May Share Information", body: "We do not sell the content of your private Winky communications. We may disclose personal information as described in this Privacy Policy, with your consent, or where permitted or required by law.\n\nOther Winky Users\n\nInformation that you choose to make visible through your Winky profile may be displayed to other Winky users. Your exact GPS coordinates, street address and precise geographic location are not displayed to other Winky users.\n\nService Providers\n\nWe may provide information to third-party service providers when reasonably necessary for them to perform services on our behalf. We expect service providers handling personal information on our behalf to use appropriate privacy and security safeguards and to process the information for the purposes for which it was provided.\n\nBusiness Transactions\n\nIf Hudson Watch Inc. is involved in a merger, acquisition, financing, restructuring, sale of assets or similar corporate transaction, information may be transferred as permitted by applicable law and subject to appropriate confidentiality and privacy protections." },
            { number: "13", title: "Legal Requests and Protection of Users", body: "We may preserve, use or disclose information when we reasonably believe that doing so is necessary or permitted to:\n\n• comply with applicable law, regulation, court order or lawful legal process;\n• respond to lawful requests from government or law-enforcement authorities;\n• investigate violations of our Terms of Service;\n• detect or prevent fraud, abuse or security threats;\n• protect the rights or property of Hudson Watch Inc.;\n• protect the safety of Winky users or the public; or\n• establish, exercise or defend legal claims.\n\nHowever, because private Winky chat messages are end-to-end encrypted, we cannot provide readable message content that we do not possess the encryption keys necessary to decrypt.\n\nWe may nevertheless be able or required to provide other account or technical information that is available to us when legally required." },
            { number: "14", title: "We Do Not Sell Personal Information", body: "Winky does not sell users' personal information in exchange for money. We do not sell the content of private Winky communications.\n\nIf our practices materially change regarding how personal information is collected, used or disclosed, we will update this Privacy Policy and provide any additional notice or choices required by applicable law." },
            { number: "15", title: "Data Security", body: "The security of your information is important to us. We use reasonable administrative, technical and organizational safeguards designed to protect personal information against unauthorized access, loss, misuse, alteration or disclosure.\n\nPrivate Winky chat messages receive the additional protection of end-to-end encryption.\n\nHowever, no Internet service, electronic transmission or information-storage system can be guaranteed to be completely secure. You are also responsible for taking reasonable steps to protect your device and Winky account from unauthorized access." },
            { number: "16", title: "Data Retention", body: "Winky retains personal information for as long as reasonably necessary to provide the Service, maintain your account, operate Winky's features, protect security, resolve disputes, enforce our agreements and comply with applicable legal obligations.\n\nBecause location is used to provide Winky's real-time proximity functionality, stored location information may be updated as a user's current location changes.\n\nDifferent categories of technical and operational information may be retained for different periods according to the purpose for which the information is required.\n\nWhen personal information is no longer reasonably required, we may delete, destroy or anonymize it, subject to applicable legal requirements." },
            { number: "17", title: "Account Deletion", body: "You may delete your Winky account using the account-deletion functionality provided within the Service.\n\nWhen your account is deleted, Winky deletes the user data associated with that account from its systems. Winky does not maintain an archive or backup copy of deleted user account data.\n\nInformation that another person has independently saved outside of Winky — for example, a screenshot saved on another person's device — is outside Winky's control and cannot be deleted by Winky.\n\nWe may retain information if and only to the extent retention is required by applicable law or a binding legal obligation." },
            { number: "18", title: "Your Privacy Rights", body: "Depending on where you live, applicable privacy laws may provide rights concerning your personal information. These may include the right to:\n\n• request access to personal information we hold about you;\n• request correction of inaccurate information;\n• withdraw consent to certain collection, use or disclosure, subject to applicable legal or contractual restrictions;\n• request deletion of personal information where applicable;\n• ask questions about our privacy practices; and\n• make a complaint regarding our handling of personal information.\n\nWe may need to verify your identity before fulfilling certain privacy requests." },
            { number: "19", title: "Consent and Device Permissions", body: "Certain Winky features require access to information or device functionality. For example, nearby discovery requires location information.\n\nWhere required, Winky will request the appropriate device permission or consent before accessing information. Depending on your device and operating system, permissions may include:\n\n• location;\n• camera;\n• photographs or media;\n• microphone;\n• notifications; and\n• other permissions required by features you choose to use.\n\nYou may change device permissions through your device settings. Withdrawing a permission may cause Winky features that depend on that permission to stop functioning." },
            { number: "20", title: "International Processing and Storage", body: "Winky uses third-party service providers and technical infrastructure that may process or store information in Canada, the United States or other jurisdictions. As a result, personal information may be processed or stored outside the province, state or country where you live.\n\nInformation processed in another jurisdiction may be subject to the laws of that jurisdiction and may be accessible to courts, law-enforcement agencies or governmental authorities in accordance with applicable law.\n\nWe take reasonable steps designed to ensure that personal information processed on our behalf receives appropriate privacy and security protection." },
            { number: "21", title: "Third-Party Services", body: "Winky may contain links to or integrate with third-party services. Those third parties may have their own privacy policies and information-handling practices.\n\nThis Privacy Policy applies to information processed by Winky and Hudson Watch Inc. It does not govern the independent practices of third parties when they process information for their own purposes.\n\nWe encourage users to review the privacy policies of third-party services they choose to use." },
            { number: "22", title: "Changes to This Privacy Policy", body: "We may update this Privacy Policy from time to time to reflect changes to Winky, our information practices, technology, legal requirements or other circumstances.\n\nWhen we update this Privacy Policy, we will revise the Last Updated date at the beginning of the Policy.\n\nIf a change materially affects how we collect, use or disclose personal information, we will provide additional notice and obtain consent where required by applicable law.\n\nWe encourage you to review this Privacy Policy periodically." },
            { number: "23", title: "Privacy Accountability", body: "Hudson Watch Inc. is responsible for personal information under its control and for maintaining appropriate privacy practices concerning Winky.\n\nQuestions, requests or complaints regarding Winky's handling of personal information may be directed to our Privacy Officer using the contact information below." },
            { number: "24", title: "Contact Us", body: "If you have questions about this Privacy Policy, Winky's privacy practices or personal information associated with your account, please contact:\n\nHudson Watch Inc.\nWINKY® — The First Hello™\nToronto, Ontario, Canada\n\nPrivacy Officer\nEmail: info@winky.com\n\nYou may also contact us to request access to or correction of personal information, exercise an applicable privacy right, or raise a concern about Winky's privacy practices." },
        ]
    },
    {
        type: 'winkyRules',
        lastUpdated: LAST_UPDATED,
        tagline: 'WINKY is built on respect and safety',
        cards: [
            {
                icon: 'hand.raised.fill',
                iconColor: 'pink',
                title: 'Consent First',
                rules: [
                    'No unsolicited calls or video calls',
                    'Messaging before calling is mandatory'
                ]
            },
            {
                icon: 'clock.fill',
                iconColor: 'orange',
                title: 'Temporary Visibility',
                rules: [
                    'User presence expires',
                    'No long-term tracking or stalking'
                ]
            },
            {
                icon: 'person.fill.checkmark',
                iconColor: 'blue',
                title: 'User Control',
                rules: [
                    'Users can block, mute, or disappear instantly',
                    'No explanation required'
                ]
            },
            {
                icon: 'exclamationmark.triangle.fill',
                iconColor: 'red',
                title: 'Zero Tolerance',
                rules: [
                    'Harassment = immediate restriction or removal',
                    'Repeat behavior = permanent ban'
                ]
            },
            {
                icon: 'shield.fill',
                iconColor: 'green',
                title: 'No Outside Pressure',
                rules: [
                    'Do not encourage sharing phone numbers or social media',
                    'WINKY is a bridge, not a data collector'
                ]
            }
        ]
    },
    {
        type: 'termsOfService',
        lastUpdated: DOC_LAST_UPDATED,
        sections: [
            { number: null, title: null, body: "Effective Date: August 24, 2026\nLast Updated: August 24, 2026\n\nWelcome to WINKY® — The First Hello™.\n\nThese Terms of Service (\"Terms\") govern your access to and use of the WINKY® mobile application and related services (collectively, the \"Service\" or \"Winky\"). Winky is owned and operated by Hudson Watch Inc. (\"Hudson Watch,\" \"Winky,\" \"we,\" \"us,\" or \"our\").\n\nPlease read these Terms carefully before creating an account or using Winky." },
            { number: "1", title: "Introduction and Acceptance of These Terms", body: "By creating a Winky account, accessing the Service, or using any Winky feature, you acknowledge that you have read, understood and agree to be bound by these Terms and our Privacy Policy.\n\nIf you do not agree to these Terms, you must not create a Winky account or access or use the Service." },
            { number: "2", title: "What Winky Is", body: "Winky is designed to help adults discover and communicate with other people nearby.\n\nWINKY® — The First Hello™ is built around a simple idea: sometimes starting a conversation is the hardest part.\n\nWinky uses proximity-based technology to help users discover other Winky users within selected geographic ranges and, where permitted by the Service, communicate with them.\n\nWinky may provide features including:\n\n• nearby user discovery;\n• proximity or discovery ranges;\n• user profiles;\n• Winks;\n• private messaging;\n• voice or video communications;\n• conversation or interaction history;\n• blocking and reporting; and\n• other social and communication features that we may introduce from time to time.\n\nWinky facilitates introductions and communications between users. Winky is not responsible for creating, supervising, verifying or guaranteeing any friendship, relationship, meeting, conversation or other interaction between users." },
            { number: "3", title: "You Must Be 18 or Older", body: "Winky is intended exclusively for adults who are 18 years of age or older. You may not create an account or use Winky if you are under 18 years of age.\n\nBy creating an account or using Winky, you represent and warrant that:\n\n1. you are at least 18 years old;\n2. you have the legal capacity to enter into these Terms; and\n3. you are not prohibited by applicable law from using the Service.\n\nIf we discover or reasonably believe that a user is under 18, we may immediately suspend or terminate the account.\n\nIf you believe that a person under 18 is using Winky, please report the account through the Service or contact us at info@winky.com." },
            { number: "4", title: "Your Winky Account", body: "You must create an account to access certain Winky features.\n\nYou agree to provide accurate information when creating and maintaining your account and not to impersonate another person or misrepresent your identity.\n\nYou are responsible for maintaining control of your account, device and authentication credentials and for activity occurring through your account. You must notify us promptly if you believe that your account has been accessed or used without authorization.\n\nYou may not create an account for another person without authorization. You may not sell, transfer, license or otherwise provide your Winky account to another person.\n\nWe reserve the right to refuse, suspend or remove a display name, username, profile photograph, bio or other account information that violates these Terms or the rights of another person." },
            { number: "5", title: "Your Name and Username", body: "Winky allows you to identify yourself to other users using the identity options made available within the Service. Depending on Winky's current features, you may be able to use your chosen name or a username.\n\nYou may not use a name or username that:\n\n• impersonates another person;\n• falsely suggests an affiliation with another person, organization or business;\n• infringes another person's trademark, copyright or other rights;\n• is fraudulent or intentionally misleading;\n• contains prohibited or seriously offensive content; or\n• otherwise violates these Terms.\n\nAny restrictions within Winky concerning how often a username or other account identifier may be changed will be disclosed through the applicable feature." },
            { number: "6", title: "Location and Nearby Discovery", body: "Location is a fundamental part of the Winky Service. With your permission, Winky uses your device's location to determine which other Winky users are within the applicable discovery range.\n\nWinky may provide discovery ranges such as:\n\n• Closest — 75 ft\n• Nearby — 300 ft\n• Walkable — 1,000 ft\n• Area — ½ mile\n\nThe available ranges may change as Winky develops.\n\nYour Exact Location\n\nWinky does not display your exact GPS coordinates, street address or precise geographic location to other Winky users. Winky uses location information to determine proximity and whether users fall within the discovery range selected within the Service.\n\nHowever, you acknowledge that another person may sometimes be able to infer your approximate location from circumstances outside Winky — for example, because you are in a small or identifiable location or because of information you voluntarily disclose. You should therefore use reasonable judgment when sharing information about your location.\n\nAccuracy of Location Information\n\nLocation and proximity information may not always be exact. Accuracy may be affected by GPS availability, device settings, buildings, network conditions, operating systems, technical limitations, delayed updates or other circumstances outside Winky's control.\n\nYou should not rely on Winky as a precise location, navigation, emergency or safety service." },
            { number: "7", title: "Private Messages and End-to-End Encryption", body: "Private Winky chat messages are protected by end-to-end encryption. End-to-end encryption is designed so that only participants in an encrypted conversation possess the ability to read the content of those messages.\n\nWinky does not possess the encryption keys necessary to decrypt and read the content of private end-to-end encrypted chat messages. Accordingly, Winky, Hudson Watch Inc., our developers, programmers, administrators and hosting providers cannot read the content of your end-to-end encrypted private chat messages.\n\nOur systems may nevertheless process limited technical information associated with communications when necessary to transmit messages, provide the Service, maintain security or troubleshoot technical problems. Such information may include sender and recipient account identifiers, timestamps, delivery information, device or application information, IP addresses and other communications metadata.\n\nYou acknowledge that end-to-end encryption protects message content within the encrypted communications system, but it cannot control what another participant does with information after receiving it. Another user may retain, copy, photograph, screenshot or otherwise preserve information that you voluntarily send or display.\n\nYou should therefore exercise judgment when sharing personal or sensitive information with another user." },
            { number: "8", title: "Winks and Communications", body: "Winky provides tools intended to help users begin conversations.\n\nReceiving a Wink, message or other communication does not create any obligation to respond. Every user has the right to decide whether or not to communicate with another user.\n\nYou must respect another user's decision not to communicate with you. You must not repeatedly contact, pressure, follow, threaten, intimidate or harass another user who has indicated that they do not wish to communicate.\n\nWhere Winky provides blocking functionality, a blocked user must not attempt to circumvent the block through another account or other means." },
            { number: "9", title: "Real-World Interactions and Personal Safety", body: "Winky helps people discover and communicate with other people nearby, but Winky does not control the conduct of its users.\n\nUnless Winky expressly states otherwise for a particular feature, we do not conduct criminal background checks on users and we do not independently verify every user's identity, age, statements, intentions, history or profile information. A Winky profile should therefore not be interpreted as a guarantee that the person is who they claim to be or that interacting with that person is safe.\n\nYou are responsible for exercising your own judgment when deciding whether to communicate with, meet or otherwise interact with another user. If you choose to meet someone you discovered through Winky, you assume responsibility for that decision and interaction.\n\nYou should never feel obligated to meet, communicate with or continue interacting with another person. If another user makes you uncomfortable, you may stop communicating, block the user and report the user to Winky.\n\nWinky is not an emergency service. If you believe that you or another person is facing an immediate emergency, contact the appropriate local emergency service." },
            { number: "10", title: "Acceptable Use and User Conduct", body: "Winky is intended to help people make genuine, respectful connections. You agree to treat other users with respect and to use Winky lawfully and responsibly.\n\nYou may not use Winky to:\n\n• threaten, bully, stalk, intimidate or harass another person;\n• repeatedly contact someone who has indicated that they do not wish to communicate;\n• impersonate another person;\n• deceive users about your identity for fraudulent or harmful purposes;\n• discriminate against or target people with hateful or abusive conduct;\n• post or transmit unlawful, threatening, defamatory or seriously offensive content;\n• distribute sexually exploitative or unlawful sexual content;\n• exploit, endanger or attempt to communicate sexually with a minor;\n• solicit or facilitate prostitution, human trafficking or sexual exploitation;\n• promote or facilitate criminal activity;\n• defraud, scam or financially exploit another person;\n• solicit money from users through deception or manipulation;\n• distribute spam or unauthorized commercial solicitations;\n• introduce malware, malicious code or other harmful technology;\n• interfere with or attempt to disrupt Winky's systems or security;\n• attempt to gain unauthorized access to another user's account;\n• scrape, harvest or systematically collect information about Winky users without authorization;\n• use automated systems, bots or scripts to access Winky except where expressly authorized by us;\n• circumvent another user's block or Winky's account restrictions;\n• violate another person's privacy, intellectual property or other legal rights; or\n• use Winky for any purpose that violates applicable law or these Terms.\n\nWe may investigate reported or suspected violations and take action we consider appropriate, including warnings, restrictions, account suspension or account termination." },
            { number: "11", title: "User Content", body: "Winky may allow you to create, upload, transmit, display or otherwise provide information, photographs, profile information, text, messages or other materials (\"User Content\").\n\nYou retain ownership of User Content that you own. You are responsible for the User Content you choose to provide through Winky and for ensuring that you have the legal right to provide it.\n\nFor User Content that must be displayed, stored, transmitted or otherwise processed to operate Winky, you grant Hudson Watch Inc. a non-exclusive, worldwide, royalty-free licence to host, store, reproduce, display, transmit and technically process that User Content only as reasonably necessary to operate, provide, secure and improve the Service, subject to our Privacy Policy.\n\nThis licence does not transfer ownership of your User Content to Winky.\n\nFor end-to-end encrypted private message content, our ability to process that content is technically limited by the encryption architecture described in these Terms and our Privacy Policy.\n\nYou represent and warrant that your User Content does not violate another person's copyright, trademark, privacy, publicity or other rights." },
            { number: "12", title: "Reporting and Blocking", body: "Winky provides tools that allow users to report another user from a chat, profile or nearby-discovery screen. Reports may be placed into a review process so that Winky can investigate reported conduct and, where appropriate, restrict, suspend or ban an account.\n\nWinky may group repeated reports concerning the same user and may impose reasonable limits on reporting activity to help prevent abuse or manipulation of the reporting system. You agree not to misuse Winky's reporting functionality or knowingly submit false, malicious or abusive reports.\n\nIf you report another user, you may voluntarily provide information, screenshots or other materials relating to the reported conduct. Information voluntarily submitted as part of a report may be reviewed for investigation, safety, enforcement and support purposes. Submitting information as part of a report does not provide Winky with general access to your other end-to-end encrypted conversations.\n\nWinky also provides blocking functionality. When you block another user, that user cannot message or call you through Winky, and you and the blocked user will no longer appear to one another through Winky's nearby-discovery functionality. Blocking is reversible through the applicable Winky functionality.\n\nWe may investigate reports and take action we consider appropriate, but we cannot guarantee that every report will result in restriction, suspension or termination of an account." },
            { number: "13", title: "No Guarantee Regarding Users", body: "Winky does not endorse any individual user.\n\nExcept where expressly stated otherwise, we make no representation or warranty regarding:\n\n• a user's identity;\n• the truth or accuracy of a user's profile;\n• a user's intentions;\n• a user's background;\n• a user's behaviour;\n• a user's relationship status;\n• compatibility between users; or\n• the outcome of any interaction or relationship.\n\nYou are responsible for evaluating the people with whom you choose to communicate or interact." },
            { number: "14", title: "Privacy", body: "Your privacy is important to us. Our collection, use, storage and disclosure of personal information are described in the WINKY® Privacy Policy, which should be read together with these Terms.\n\nBy using the Service, you acknowledge that your personal information will be handled as described in our Privacy Policy and in accordance with applicable law." },
            { number: "15", title: "Intellectual Property", body: "The Winky Service and all materials owned by Hudson Watch Inc., including without limitation software, code, designs, graphics, logos, icons, text, interfaces, features, functionality and other proprietary materials (\"Winky Content\"), are owned by Hudson Watch Inc. or its licensors and are protected by applicable copyright, trademark and other intellectual property laws.\n\nWINKY®, The First Hello™, Winky logos, branding and associated marks are trademarks or intellectual property of Hudson Watch Inc. or are used by Hudson Watch Inc. under applicable rights.\n\nExcept for the limited right to use the Service in accordance with these Terms, no right, title or interest in Winky or Winky Content is transferred to you.\n\nYou may not copy, reproduce, modify, distribute, sell, license, reverse engineer, decompile, attempt to extract source code from, create derivative works from or commercially exploit Winky or Winky Content except where expressly permitted by law or authorized by us in writing." },
            { number: "16", title: "Limited Licence to Use Winky", body: "Subject to your compliance with these Terms, Hudson Watch Inc. grants you a limited, personal, non-exclusive, non-transferable, non-sublicensable and revocable licence to download, access and use Winky for your personal, non-commercial use.\n\nThis licence terminates automatically when your account is terminated or when you cease to be entitled to use the Service." },
            { number: "17", title: "Third-Party Services", body: "Winky may use or integrate technology, infrastructure or services supplied by third parties. Winky may also contain links to third-party websites, applications or services.\n\nHudson Watch Inc. does not control third-party services and is not responsible for their independent content, availability, security, privacy practices or conduct.\n\nYour use of a third-party service may be subject to that provider's own terms and privacy policy." },
            { number: "18", title: "Availability and Changes to the Service", body: "We work to provide a reliable Service, but we do not guarantee that Winky will always be available, uninterrupted or error-free.\n\nWe may from time to time:\n\n• modify Winky;\n• add or remove features;\n• change discovery ranges;\n• update technical requirements;\n• perform maintenance;\n• suspend features;\n• discontinue features; or\n• discontinue all or part of the Service.\n\nWe may make these changes when reasonably necessary for technical, operational, security, legal or business reasons." },
            { number: "19", title: "Suspension, Restrictions and Termination", body: "We may suspend, restrict or terminate your access to Winky if we reasonably believe that:\n\n• you violated these Terms;\n• you created a risk to another user;\n• you engaged in fraudulent, abusive or unlawful conduct;\n• your account presents a security risk;\n• your use of Winky may expose Hudson Watch Inc. or another person to legal liability; or\n• suspension or termination is otherwise reasonably necessary to protect Winky, our users or the Service.\n\nSerious or repeated violations may result in immediate termination or a ban from the Service.\n\nWhere appropriate, we may take reasonable technical measures designed to prevent a user whose account has been banned or restricted from circumventing that action by deleting the account and creating another account." },
            { number: "20", title: "Account Deletion", body: "You may delete your Winky account using the account-deletion functionality provided within the Service.\n\nWhen you delete your account, Winky deletes the personal account and profile information associated with that account from its active systems, including your name, telephone number, email address, profile photograph and stored location history.\n\nMessages and records of calls that you previously sent or made to other Winky users may remain in those users' conversation or communication histories. After your account is deleted, those communications will no longer be displayed as originating from your active Winky profile and may instead appear as originating from a deleted user.\n\nWinky may retain a limited record after account deletion for legitimate operational purposes, including maintaining aggregate statistics concerning accounts that joined and left the Service and helping prevent a person whose account was banned or restricted from circumventing that action by deleting the account and creating another account. Winky limits such retained information to what is reasonably necessary for those purposes and handles it in accordance with the WINKY® Privacy Policy and applicable law.\n\nInformation that another person has independently retained outside Winky, such as a screenshot, photograph or other copy stored on another person's device, is outside Winky's control.\n\nDeleting your account terminates your right to use the Service but does not affect provisions of these Terms that by their nature are intended to survive termination." },
            { number: "21", title: "Disclaimer of Warranties", body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WINKY IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS.\n\nHUDSON WATCH INC. DOES NOT WARRANT THAT:\n\n• THE SERVICE WILL ALWAYS BE AVAILABLE OR UNINTERRUPTED;\n• THE SERVICE WILL BE COMPLETELY ERROR-FREE;\n• LOCATION OR PROXIMITY INFORMATION WILL ALWAYS BE PRECISE;\n• EVERY USER WILL PROVIDE ACCURATE INFORMATION;\n• EVERY USER WILL BEHAVE APPROPRIATELY;\n• THE SERVICE WILL RESULT IN ANY PARTICULAR FRIENDSHIP, RELATIONSHIP, MEETING OR OTHER OUTCOME; OR\n• EVERY SECURITY RISK OR UNAUTHORIZED ACTIVITY CAN BE PREVENTED.\n\nTO THE EXTENT PERMITTED BY LAW, WE DISCLAIM WARRANTIES AND CONDITIONS THAT ARE NOT EXPRESSLY PROVIDED IN THESE TERMS, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.\n\nNothing in these Terms excludes any warranty, condition, right or remedy that cannot lawfully be excluded under applicable law." },
            { number: "22", title: "Assumption of Risk Regarding User Interactions", body: "You acknowledge that communicating or meeting with people whom you do not already know involves risks that Winky cannot completely eliminate.\n\nYou voluntarily assume the risks associated with your interactions with other users to the extent permitted by applicable law.\n\nHudson Watch Inc. is not responsible for the independent acts or omissions of users outside our reasonable control.\n\nNothing in these Terms is intended to exclude or limit liability that cannot legally be excluded or limited." },
            { number: "23", title: "Limitation of Liability", body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HUDSON WATCH INC. AND ITS AFFILIATES, DIRECTORS, OFFICERS, EMPLOYEES, CONTRACTORS, DEVELOPERS, AGENTS AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO YOUR USE OF OR INABILITY TO USE WINKY.\n\nTHIS INCLUDES, TO THE EXTENT PERMITTED BY LAW, DAMAGES ARISING FROM:\n\n• LOSS OF DATA;\n• LOSS OF PROFITS OR BUSINESS OPPORTUNITIES;\n• INTERRUPTION OF SERVICE;\n• USER CONTENT;\n• UNAUTHORIZED ACCESS TO AN ACCOUNT;\n• THE CONDUCT OF ANOTHER USER;\n• COMMUNICATIONS BETWEEN USERS;\n• MEETINGS OR OTHER INTERACTIONS BETWEEN USERS;\n• RELIANCE ON LOCATION OR PROXIMITY INFORMATION; OR\n• THIRD-PARTY SERVICES.\n\nWINKY DOES NOT CONTROL AND, TO THE MAXIMUM EXTENT PERMITTED BY LAW, IS NOT RESPONSIBLE FOR THE INDEPENDENT CONDUCT OF USERS OR THIRD PARTIES.\n\nNothing in these Terms excludes or limits liability where such exclusion or limitation is prohibited by applicable law." },
            { number: "24", title: "Indemnification", body: "To the extent permitted by applicable law, you agree to indemnify and hold harmless Hudson Watch Inc. and its affiliates, directors, officers, employees, contractors and agents from claims, losses, liabilities, damages, costs and reasonable legal expenses arising from or relating to:\n\n• your unlawful use of Winky;\n• your material violation of these Terms;\n• User Content you provide;\n• your violation of another person's rights; or\n• your fraud, wilful misconduct or unlawful conduct.\n\nHudson Watch Inc. reserves the right to participate in the defence or settlement of any matter subject to indemnification." },
            { number: "25", title: "No Waiver", body: "If Hudson Watch Inc. does not immediately enforce a provision of these Terms, that does not mean we have waived our right to enforce that provision later.\n\nA waiver of any provision is effective only if expressly made by us in writing." },
            { number: "26", title: "Severability", body: "If any provision of these Terms is determined by a court of competent jurisdiction to be invalid, unlawful or unenforceable, that provision will be interpreted or limited to the minimum extent necessary to make it enforceable where legally permissible.\n\nThe remaining provisions will continue in full force and effect." },
            { number: "27", title: "Assignment", body: "You may not assign or transfer your rights or obligations under these Terms without our prior written consent.\n\nHudson Watch Inc. may assign or transfer its rights and obligations under these Terms as part of a merger, acquisition, corporate reorganization, financing, sale of assets or similar transaction, subject to applicable law." },
            { number: "28", title: "Governing Law", body: "These Terms and your use of Winky are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict-of-law principles.\n\nSubject to any rights that you may have under applicable consumer protection or other mandatory laws, disputes arising from or relating to these Terms or Winky will be subject to the jurisdiction of the courts located in Ontario, Canada.\n\nNothing in these Terms deprives you of protections or rights that cannot lawfully be waived under the laws applicable to you." },
            { number: "29", title: "Changes to These Terms", body: "We may update these Terms from time to time to reflect changes to Winky, our business, technology, legal requirements or other circumstances.\n\nWhen we update these Terms, we will revise the Last Updated date at the beginning of the Terms.\n\nIf a change materially affects your rights or obligations, we will provide reasonable notice where required by applicable law. Where legally required, we may ask you to affirmatively accept updated Terms before continuing to use Winky.\n\nIf you do not agree to updated Terms, you must stop using Winky and may delete your account." },
            { number: "30", title: "Entire Agreement", body: "These Terms, together with the WINKY® Privacy Policy and any additional terms expressly presented to you for a particular Winky feature, constitute the agreement between you and Hudson Watch Inc. concerning your use of the Service.\n\nIf additional terms applicable to a particular feature conflict with these Terms, the additional terms will govern with respect to that feature to the extent of the conflict." },
            { number: "31", title: "Contact Us", body: "If you have questions about these Terms, need assistance with your Winky account, or wish to report a concern, please contact:\n\nHudson Watch Inc.\nWINKY® — The First Hello™\nToronto, Ontario, Canada\n\nEmail: info@winky.com\n\nWINKY® — The First Hello™\nBecause every friend was once a stranger." },
        ]
    }
];

async function run() {
    await mongoose.connect(process.env.MONGO_HOST);
    console.log('Connected to MongoDB');

    for (const seed of seeds) {
        const { type, ...data } = seed;
        await LegalContent.findOneAndUpdate({ type }, { type, ...data }, { upsert: true, new: true });
        console.log(`✓ Upserted: ${type}`);
    }

    await mongoose.disconnect();
    console.log('Done.');
}

run().catch(err => { console.error(err); process.exit(1); });
